# Actionlint configuration for FollowWeb
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Shellcheck configuration
# Actionlint integrates shellcheck to validate shell scripts in workflow 'run:' steps
# We configure it to ignore style suggestions and info-level issues that don't affect functionality

self-hosted-runner:
  # No self-hosted runners
  labels: []

# Shellcheck integration settings
# Exclude codes that are style preferences or don't apply to GitHub Actions context
shellcheck:
  # Exclude shellcheck codes:
  # SC2148 - missing shebang (GitHub Actions doesn't require shebangs)
  # SC1091 - not following sourced files (external files not available in CI)
  # SC2164 - cd without error handling (CI stops on any failure)
  # SC2129 - grouped redirects (style preference, not a bug)
  # SC2086 - double quote to prevent globbing (often intentional in CI scripts)
  # SC2034 - unused variables (often used for documentation or future use)
  exclude-codes:
    - SC2148
    - SC1091
    - SC2164
    - SC2129
    - SC2086
    - SC2034
