instagram:
  username: "username"

scraper:
  output_file: "followers.json"
  depth: 1 

visualization:
  input_file: "followers.json"
  pruning:
    min_connections: 6
  visualization_settings:
    width: "100%"
    height: "90vh"
    notebook: False
    base_node_size: 10
    node_size_multiplier: 8
    scaling_algorithm: "logarithmic"
